superlists/lists/urls.py
from django.urls import path
from .views import home_page
from .views import view_list
from .views import new_list
from .views import add_item


app_name = 'lists'

urlpatterns = [
    path('', home_page, name='home_page'),
    path('<int:list_id>/', view_list, name='view_list'),
    path('<int:list_id>/add_item', add_item, name='add_item'),
    path('new', new_list, name='new_list'),
]

superlists/superlists/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from lists.views import home_page


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', home_page),
    path('lists/', include('lists.urls')),
]

superlists/lists/models.py
from django.db import models


class List(models.Model):
    pass


# Create your models here.
class Item(models.Model):
    text = models.CharField(max_length=255, default="nothing...")
    todo_list = models.ForeignKey(List, on_delete=models.CASCADE, default=None)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.text

superlists/lists/views.py
from .models import Item
from .models import List

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.urls import reverse


# Create your views here.
def home_page(request):
    return render(request, 'lists/home_page.html')


def view_list(request, list_id):
    todo_list = get_object_or_404(List, pk=list_id)
    items = todo_list.item_set.all()
    context = dict(
        items=items,
        todo_list=todo_list,
    )
    return render(request, 'lists/view_list.html', context)


def new_list(request):
    todo_list = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], todo_list=todo_list)
    return redirect(reverse('lists:view_list', args=(todo_list.id, )))


def add_item(request, list_id):
    todo_list = get_object_or_404(List, pk=list_id)
    item_text = request.POST['item_text']
    Item.objects.create(text=item_text, todo_list=todo_list)
    #return redirect(f'/lists/{list_id}/')
    return redirect(reverse('lists:view_list', args=(list_id,)))

superlists/lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
    <title>To-Do lists</title>
</head>
<body>
    <div class="container row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">

            <h1>{% block header_text %} {% endblock %}</h1>

            <form action="{% block form_action %} {% endblock %}" method="POST">
              {% csrf_token %}
              <input type="text"  id="id_new_item" name="item_text" class="form-control input-lg id-new-item" value="" placeholder="Enter a to-do item" >
            </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

    </div>

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

superlists/lists/templates/lists/home_page.html
{% extends 'base.html' %}
{% block header_text %}Start a new To-Do lists {% endblock %}
{% block form_action %} {% url 'lists:new_list' %} {% endblock %}

superlists/lists/templates/lists/view_list.html
{% extends 'base.html' %}
{% block header_text %}To-Do lists{% endblock %}
{% block form_action %} /lists/{{todo_list.id}}/add_item {% endblock %}

{% block table %}
    <table id='id_list_table' class="table">
        {% for item in items %}
        <tr>
            <td>{{forloop.counter}}:{{ item.text }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}